// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnymarwhxonvmfkgutax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRueW1hcndoeG9udm1ma2d1dGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1OTgwNTEsImV4cCI6MjA3NDE3NDA1MX0.eSK2mdB-YB20b8t_5yBjCUGB_Z-oTz-1aGVnslYgzGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});